### ISSUE TITLE
Render register form as a bootstrap form

### ISSUE THREAD

**Issue by t-bello7** [Call-for-Code-for-Racial-Justice/Legit-Info#118]
### Background on the problem the feature will solve/improve user experience

The register form renders the form element as a paragraph. Changing the elements to render as a bootstrap form would allow the validations to be done easily.

### Describe the solution you'd like

Render the register form with bootstrap.

### Tasks
- Render the register form with bootstrap.
- Add the custom validation with javascript.

### Acceptance Criteria
The form is more accessible and readable for the user. Validation of each input before the user clicks on the submit button allows a better user experience.

**Comment by upkarlidder** [comment]
@t-bello7 to open a new PR.
