### ISSUE TITLE
Use IBM Watson NLU to narrow the location scope to county or city, based on concept returned.

### ISSUE THREAD

**Issue by tonypearson** [Call-for-Code-for-Racial-Justice/Legit-Info#30]
This may involve automatically adding County and City locations as appropriate.

**Comment by tnadams** [comment]
Suggest to do this in Python without Watson NLU since it is basically just string matching. Can save on some NLU transactions costs and probably a bit faster as well. I linked a possible Python solution as PR#37 to this issue.

**Comment by tonypearson** [comment]
Consider doing pattern matching instead.

**Comment by tonypearson** [comment]
Re-open for consideration
