### ISSUE TITLE
Activate and implement "Django Test" function

### ISSUE THREAD

**Issue by tonypearson** [Call-for-Code-for-Racial-Justice/Legit-Info#31]
Currently, the only testing features we have is DEBUG=True and  ./stage1 testserver cfc-seed.json 
There are more features and we can figure out better test automation options.

**Comment by tonypearson** [comment]
New environment variable CFC_DEBUG = 'True' or "False" allows option to be changed dynamically when needed.

**Comment by tnadams** [comment]
I looked into Django Test which uses Python unittest, but it looks a little more extensive than we need right now for the size of this app. We would probably want to look into bringing in a test framework and test automation later in development, so closing for now.

**Comment by tonypearson** [comment]
Re-open for consideration
