### ISSUE TITLE
Collect all 50 states, the top 10 most populous cities in those states, and the counties those top 10 cities are in

### ISSUE THREAD

**Issue by tonypearson** [Call-for-Code-for-Racial-Justice/Legit-Info#43]

**Comment by tnadams** [comment]
I found a source which provides a CSV and XLS file with around 30,000 US cities along with county, state, and population data. We can use this as the primary source and whittle down to a more manageable chunk of cities/counties to start, with the option to consume the whole list in the future. I'll push both lists in a PR later today.

https://simplemaps.com/data/us-cities

**Comment by tnadams** [comment]
Here is the license for the data from simplemaps.com. Legal might need to review, but looks like we can use the data if we link to the source in our app. We are using the "Free US Cities Database" portion of the database.

This license is a legal document designed to protect your rights and the rights of the Pareto Software, LLC, the owner of Simplemaps.com. Please read it carefully. Purchasing or downloading a data product constitutes acceptance of this license.

Description of Product and Parties: This license is a contract between you (hereafter, the Customer) and Pareto Software, LLC (hereafter, the Provider) regarding the use and/or sale of an collection of geographic data (hereafter, the Database).

Ownership of Database: All rights to the Database are owned by the Provider. The Database is a cleaned and curated collection of geographic facts and the Provider retains all rights to the Database afforded by the law. Ownership of any intellectual property generated by the Provider while performing custom modifications to the Database for a Customer (with or without payment) is retained by the Provider.

License: Customers who purchase a license are allowed to use the database for projects that benefit their organization or that their organization oversees. Attribution is not required. The Customer is allowed to query the database to power privately or publicly facing applications. The Customer is allowed to make copies and backups of the data. The Customer may not publicly redistribute the Database without prior written permission. Customers can transfer their license to a third-party, at the sole discretion of the Provider, by submitting a request via email.

Free US Zip Code Database: The Provider offers a free version of the US Zip Code Database. This Database is offered free of charge conditional on a link back to https://simplemaps.com/data/us-zips. This backlink must come from a public webpage where the Customer is using the data. If the Customer uses the data internally, the backlink must be placed on the organization's website on a page that can be easily found though links on the root domain. The link must be clearly visible to the human eye. The backlink must be placed before the Customer uses the Database in production.

Free US Cities Database: The Provider offers a free version of the US Cities Database. This Database is offered free of charge conditional on a link back to https://simplemaps.com/data/us-cities. This backlink must come from a public webpage where the Customer is using the data. If the Customer uses the data internally, the backlink must be placed on the organization's website on a page that can be easily found though links on the root domain. The link must be clearly visible to the human eye. The backlink must be placed before the Customer uses the Database in production.

Basic World Cities Database: The Provider offers a Basic World Cities Database free of charge. This database is licensed under the MIT license as described at: https://opensource.org/licenses/MIT.

Comprehensive World Cities Database Density Data: The Comprehensive World Cities Database includes density estimates from The Center for International Earth Science Information Network - CIESIN - Columbia University. 2016. Gridded Population of the World, Version 4 (GPWv4): Population Count. Palisades, NY: NASA Socioeconomic Data and Applications Center (SEDAC). http://dx.doi.org/10.7927/H4X63JVC. Accessed June 2017. The density estimates are include under the Creative Commons Attribution 4.0 International License. The Provider places no additional restrictions on the use or distribution of the density data.

Guarantee: The Provider guarantees that for the period of thirty (30) days from the purchase of a License that the Customer shall, upon request, be refunded their actual purchase price within a reasonable period of time. The Customer acknowledges that receipt of a refund constitutes a termination of their License to use the Database. In the event of a Refund, the Customer promises to delete the Database immediately. Refunds after the period of thirty (30) days shall be at the sole discretion of the Provider.

LIMITATION OF LIABILITY: THE DATABASE IS SOLD "AS IS" AND "WITH ALL FAULTS". THE PROVIDER MAKES NO WARRANTY THAT IT IS FREE OF DEFECTS OR IS SUITABLE FOR ANY PARTICULAR PURPOSE. IN NO EVENT SHALL THE PROVIDER BE RESPONSIBLE FOR LOSS OR DAMAGES ARRISING FROM THE INSTALLATION OR USE OF THE DATABASE, INCLUDING BUT NOT LIMITED TO ANY INDIRECT, PUNITIVE, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES. THE CUSTOMER IS SOLELY RESPONSIBLE FOR ENSURING THAT THEIR USE OF THE DATABASE IS IN ACCORDANCE WITH THE LAW OF THEIR JURISDICTION.

PROHIBITION OF ILLEGAL USE: USE OF THE DATABASE WHICH IS CONTRARY TO THE LAW IS PROHIBITED, AND IMMEDIATELY TERMINATES THE CUSTOMER'S LICENSE TO USE THE DATABASE.

**Comment by tonypearson** [comment]
Re-open for consideration.  We have the data, but need to enter it into the database or have it in "loadable" format.

**Comment by upkarlidder** [comment]
I am doing some exploratory analysis on the free data dump from simplemaps:

Number of entries in states: 52
```
['New York', 'California', 'Illinois', 'Florida', 'Texas',
       'Pennsylvania', 'Georgia', 'District of Columbia', 'Massachusetts',
       'Arizona', 'Washington', 'Michigan', 'Minnesota', 'Colorado',
       'Maryland', 'Nevada', 'Oregon', 'Missouri', 'Ohio', 'Indiana',
       'North Carolina', 'Virginia', 'Wisconsin', 'Rhode Island', 'Utah',
       'Tennessee', 'Louisiana', 'Kentucky', 'Oklahoma', 'Connecticut',
       'Nebraska', 'Hawaii', 'New Mexico', 'Alabama', 'South Carolina',
       'Kansas', 'Iowa', 'Arkansas', 'Idaho', 'Mississippi',
       'Puerto Rico', 'New Jersey', 'Alaska', 'New Hampshire',
       'North Dakota', 'Maine', 'South Dakota', 'West Virginia',
       'Montana', 'Delaware', 'Vermont', 'Wyoming']
```

Total cities in each state:
```
Texas                   1679
Pennsylvania            1649
California              1470
Illinois                1362
Ohio                    1202
Missouri                1020
Iowa                    1003
Florida                  911
Minnesota                896
New York                 880
Wisconsin                773
North Carolina           733
Oklahoma                 732
Michigan                 689
Indiana                  677
Kansas                   669
Georgia                  617
Washington               609
Virginia                 586
Alabama                  581
Nebraska                 576
Kentucky                 538
Arkansas                 536
Maryland                 510
New Jersey               508
Louisiana                474
Colorado                 448
Tennessee                427
Arizona                  427
New Mexico               425
West Virginia            401
North Dakota             397
South Carolina           394
South Dakota             382
Oregon                   373
Mississippi              361
Montana                  360
Alaska                   326
Utah                     322
Puerto Rico              243
Idaho                    226
Wyoming                  186
Hawaii                   149
Massachusetts            139
Nevada                   125
Connecticut              110
Delaware                  77
Vermont                   48
Maine                     41
New Hampshire             38
Rhode Island              32
District of Columbia       1
```
