### ISSUE TITLE
Improve the Setup Process in the README

### ISSUE THREAD

**Issue by TrevorFreudig** [Call-for-Code-for-Racial-Justice/Legit-Info#51]
## Description of Changes

1. Under the "Getting Started" section in the README, the setup instructions need more detail. The entire process is laid out nicely [here](https://developer.ibm.com/tutorials/legit-info/) and it would be beneficial to have this laid out directly in the README. By having this information directly located in the README, it will make the setup process much easier for new contributors.
2. Create a new AUTHORS.md file to contain the authors section currently found in the README. This will help with the readability of the README.
3. Specify what each technology found in the "Built with IBM and Open Source technologies" section will be used for. This will help new contributors understand what they need to install based on what they want to contribute to the project. Ex. If someone simply wants to contribute to the UI, explain which technologies they will need on their local system.

**Comment by Stig124** [comment]
Hello,

I can help with that
