### ISSUE TITLE
ValueError at results/58

### ISSUE THREAD

**Issue by tonypearson** [Call-for-Code-for-Racial-Justice/Legit-Info#53]
Residual data in database table points to non-existent results CSV file.

**Comment by rohitkpa** [comment]
Hey @tonypearson, @twan-westerhof and I have found out that there's a discrepancy between how non-existent results CSV files are handled between Windows and Mac users. When Mac users search with any combination of Location and Impact where there is no resulting CSV file in the results folder, a new file is generated without returning the `ValueError at results/<file-number>`. However for a Windows user, the file is not generated and the ValueError is displayed on the front end. For reference, this is using the `stage1` development setup. Following the [instructions](https://developer.ibm.com/tutorials/legit-info/), when the command `./stage1 loaddata cfc-seed.json` is executed on a Mac, the results folder is populated. However for Windows, the results folder only includes the README.md file.
