### ISSUE TITLE
Implement Django.q schedular for weekly jobs since CRON not available in IBM Cloud Foundry

### ISSUE THREAD

**Issue by tonypearson** [Call-for-Code-for-Racial-Justice/Legit-Info#57]
Implement "django_q" to schedule weekly tasks for:  get_datasets,  extract_files, and analyze_text functions.

**Comment by krook** [comment]
You might also look at whether a cron trigger to invoke an IBM Cloud Function might serve this purpose.

Here's an older example of the approach: https://github.com/IBM/ibm-cloud-functions-action-trigger-rule

**Comment by tonypearson** [comment]
@krook It would be best to have something that is consistent between all three stages.

Django_q appears to work find.  For stages 1 and 2, you start up a second terminal and run ".stageN qcluster"
which allows up to four concurrent asynchronous background tasks.  The tasks themselves can be configured and scheduled directly from the applications "Admin" panel.

We will now need to figure out how to get this additional process running as a "sidecar" on IBM Cloud Foundry.

**Comment by tonypearson** [comment]
Done.
