### ISSUE TITLE
Logging in legislation processing seems too strict

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Legit-Info#85]
@tonypearson @tnadams: current extract_files.py seems too restrictive. For example in `cfc_app/management/commands/extract_files.py`, we error out on 
- parse error
- binary data is not downloaded
- binary data is corrupt 

These problems are definitely errors, however, they stop the whole job and not just the current bill when we raise an error. Instead, I propose we collect these errors in the database to look at later and not stop the job itself. Thoughts?

I have commented out `raise ExtractTextError from exc` and `raise LegiscanError(ftext) from exc` for now in a different branch to see if the job finished all the files.

**Comment by tnadams** [comment]
Makes sense to me. I reviewed the code and made one small comment but, other than that, it looks good pending a test run.

**Comment by upkarlidder** [comment]
Thank you @tnadams. After further investigation, the problem is `raise exception` and not `logger.error`. I don't think logger.error stops the program. The raise exception on the other hand does. I am going to move it back and remove the raise statements and try again. Will create a PR.
