### ISSUE TITLE
Move to call for code NLU account

### ISSUE THREAD

**Issue by upkarlidder** [Call-for-Code-for-Racial-Justice/Legit-Info#90]
Change NLU credentials in Code Engine secret to the NLU service hosted on Call for Code account.

Related to #89

**Comment by johnwalicki** [comment]
Thanks @upkarlidder  - Let me know via a @ mention when this is complete.  I'll delete the NLU service instance over in my org (which has a monthly charge)

**Comment by upkarlidder** [comment]
@johnwalicki I forgot to close out the issue. Thank you for your patience.

**Comment by johnwalicki** [comment]
@upkarlidder  Can I delete the NLU instance that is incurring charges against my dept?

**Comment by upkarlidder** [comment]
Yes, this app now uses NLU in CfC account.

**Comment by johnwalicki** [comment]
Thanks  I've cleaned up my account.
