### ISSUE TITLE
Change tooltip for "no legislation' selected error

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Legit-Info#97]
## Background

Steps:
When user click search legislation without selecting legislation a tooltip pops up

<img width="1151" alt="Screen Shot 2021-09-24 at 4 32 40 PM" src="https://user-images.githubusercontent.com/3202514/134746212-432554a9-9b3b-4768-bb98-be54290d4431.png">

## Solution
- This is bad for accessibility for issues, 
- Show on page not as pop up

**Comment by demilolu** [comment]
Alright! go for it! @dmtrek14

**Comment by upkarlidder** [comment]
Finished. Thank you @dmtrek14
